version: '3'
services:
  api:
    container_name: dev_api
    environment:
      PGUSER: ${DATABASE_USER}
      PGHOST: db
      PGPASSWORD: ${DATABASE_PASS}
      PGDATABASE: ${DATABASE_NAME}
      PGPORT: 5432
      PORT: 5000
    depends_on:
      - db
    ports:
      - 5000:${API_PORT}
    command: sh -c "npm i && npm run dev"
  db:
    container_name: dev_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
networks:
  default:
    name: dev